In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px

In [ ]:
rating = pd.read_csv('ratings.csv')
rating

          userId  movieId  rating   timestamp
0              1       17     4.0   944249077
1              1       25     1.0   944250228
2              1       29     2.0   943230976
3              1       30     5.0   944249077
4              1       32     5.0   943228858
...          ...      ...     ...         ...
32000199  200948    79702     4.5  1294412589
32000200  200948    79796     1.0  1287216292
32000201  200948    80350     0.5  1294412671
32000202  200948    80463     3.5  1350423800
32000203  200948    87304     4.5  1350423523

[32000204 rows x 4 columns]

In [ ]:
movies = pd.read_csv('movies.csv')
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
87580,292731,The Monroy Affaire (2022),Drama
87581,292737,Shelter in Solitude (2023),Comedy|Drama
87582,292753,Orca (2023),Drama
87583,292755,The Angry Breed (1968),Drama
87584,292757,Race to the Summit (2023),Action|Adventure|Documentary

In [ ]:
rating.drop('timestamp', axis= 1, inplace= True)

rating.duplicated().sum()

0

In [ ]:
rating.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32000204 entries, 0 to 32000203
Data columns (total 3 columns):
 #   Column   Dtype
---  ------   -----
 0   userId   int64
 1   movieId  int64
 2   rating   float64
dtypes: float64(1), int64(2)
memory usage: 732.4 MB

In [ ]:
rating['movieId'].min()

1

In [ ]:
rating['movieId'].max()

292757

In [ ]:
rating['userId'].astype('int32')

0                1
1                1
2                1
3                1
4                1
             ...
32000199    200948
32000200    200948
32000201    200948
32000202    200948
32000203    200948
Name: userId, Length: 32000204, dtype: int32

In [ ]:
pd.to_numeric(rating['userId'], downcast= 'integer')

0                1
1                1
2                1
3                1
4                1
             ...
32000199    200948
32000200    200948
32000201    200948
32000202    200948
32000203    200948
Name: userId, Length: 32000204, dtype: int32

In [ ]:
rating['userId'] = rating['userId'].astype('int32')
rating['movieId'] = rating['movieId'].astype('int32')
rating['rating'] = rating['rating'].astype('Float32')

In [ ]:
rating.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32000204 entries, 0 to 32000203
Data columns (total 3 columns):
 #   Column   Dtype
---  ------   -----
 0   userId   int32
 1   movieId  int32
 2   rating   Float32
dtypes: Float32(1), int32(2)
memory usage: 396.7 MB

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87585 entries, 0 to 87584
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  87585 non-null  int64
 1   title    87585 non-null  object
 2   genres   87585 non-null  object
dtypes: int64(1), object(2)
memory usage: 2.0+ MB

In [ ]:
movies['movieId'] = movies['movieId'].astype('int32')

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87585 entries, 0 to 87584
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  87585 non-null  int32
 1   title    87585 non-null  object
 2   genres   87585 non-null  object
dtypes: int32(1), object(2)
memory usage: 1.7+ MB

In [ ]:
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
87580,292731,The Monroy Affaire (2022),Drama
87581,292737,Shelter in Solitude (2023),Comedy|Drama
87582,292753,Orca (2023),Drama
87583,292755,The Angry Breed (1968),Drama
87584,292757,Race to the Summit (2023),Action|Adventure|Documentary

In [ ]:
movies['genres'] = movies['genres'].str.replace('|', ' ')
movies['genres']

0        Adventure Animation Children Comedy Fantasy
1                         Adventure Children Fantasy
2                                     Comedy Romance
3                               Comedy Drama Romance
4                                             Comedy
                            ...
87580                                          Drama
87581                                   Comedy Drama
87582                                          Drama
87583                                          Drama
87584                   Action Adventure Documentary
Name: genres, Length: 87585, dtype: object

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf_idf = TfidfVectorizer(dtype= np.float32)

tfidf_matrix = tf_idf.fit_transform(movies['genres'])

In [ ]:
pd.DataFrame(data= tfidf_matrix.toarray(), columns= tf_idf.get_feature_names_out())

,action,adventure,animation,children,comedy,crime,documentary,drama,fantasy,fi,...,listed,musical,mystery,no,noir,romance,sci,thriller,war,western
0,0.000000,0.458969,0.478003,0.480576,0.282693,0.0,0.000000,0.000000,0.499992,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
1,0.000000,0.551895,0.000000,0.577877,0.000000,0.0,0.000000,0.000000,0.601223,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
2,0.000000,0.000000,0.000000,0.000000,0.596953,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.802276,0.0,0.0,0.0,0.0
3,0.000000,0.000000,0.000000,0.000000,0.534581,0.0,0.000000,0.445028,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.718452,0.0,0.0,0.0,0.0
4,0.000000,0.000000,0.000000,0.000000,1.000000,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87580,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
87581,0.000000,0.000000,0.000000,0.000000,0.768544,0.0,0.000000,0.639797,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
87582,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
87583,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
87584,0.541021,0.639301,0.000000,0.000000,0.000000,0.0,0.546434,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0

In [ ]:
rating

          userId  movieId  rating
0              1       17     4.0
1              1       25     1.0
2              1       29     2.0
3              1       30     5.0
4              1       32     5.0
...          ...      ...     ...
32000199  200948    79702     4.5
32000200  200948    79796     1.0
32000201  200948    80350     0.5
32000202  200948    80463     3.5
32000203  200948    87304     4.5

[32000204 rows x 3 columns]

In [ ]:
rating['userId'].max()

200948

In [ ]:
rating['movieId'].unique()

array([    17,     25,     29, ..., 175771, 157917, 274343])

In [ ]:
rating['movieId'].nunique()

84432

In [ ]:
for idx, i in enumerate(['ahmed', 'ali', 'zaki']):
    print(idx, i)

0 ahmed
1 ali
2 zaki

In [ ]:
# d = {}
# for idx, i in enumerate(rating['movieId']):

#     d[i] = idx

In [ ]:
# Take unique movie ids from movies table
movie_idx = {val : idx for idx, val in enumerate(movies['movieId'])}
# Then map these values to moviedId in rating table
rating['movie_idx'] = rating['movieId'].map(movie_idx)

In [ ]:
rating

          userId  movieId  rating  movie_idx
0              1       17     4.0         16
1              1       25     1.0         24
2              1       29     2.0         28
3              1       30     5.0         29
4              1       32     5.0         31
...          ...      ...     ...        ...
32000199  200948    79702     4.5      15058
32000200  200948    79796     1.0      15077
32000201  200948    80350     0.5      15212
32000202  200948    80463     3.5      15240
32000203  200948    87304     4.5      16546

[32000204 rows x 4 columns]

In [ ]:
from scipy.sparse import csr_matrix

user_movie_matrix = csr_matrix( (rating['rating'], (rating['userId'], rating['movie_idx'])), dtype= np.float32)

In [ ]:
user_movie_matrix

<Compressed Sparse Row sparse matrix of dtype 'float32'
	with 32000204 stored elements and shape (200949, 87585)>

In [ ]:
tfidf_matrix.shape

(87585, 24)

In [ ]:
user_movie_matrix.shape

(200949, 87585)

In [ ]:
user_profile = user_movie_matrix @ tfidf_matrix

In [ ]:
user_profile

<Compressed Sparse Row sparse matrix of dtype 'float32'
	with 3620766 stored elements and shape (200949, 24)>

In [ ]:
len(tf_idf.get_feature_names_out())

24

In [ ]:
pd.DataFrame(data= user_profile.toarray(), columns= tf_idf.get_feature_names_out())

,action,adventure,animation,children,comedy,crime,documentary,drama,fantasy,fi,...,listed,musical,mystery,no,noir,romance,sci,thriller,war,western
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,37.011974,32.016247,0.000000,6.286689,110.433548,45.826733,3.000000,205.947266,14.099378,34.773540,...,0.000000,0.000000,24.196714,0.000000,2.768587,82.288811,34.773540,25.084921,60.280472,5.469484
2,19.016384,15.327096,17.693815,28.004452,61.132198,14.059561,0.000000,54.794159,8.987656,0.000000,...,0.000000,19.456257,3.761593,0.000000,0.000000,64.104462,0.000000,28.785210,5.917781,0.000000
3,101.823502,115.161575,21.760843,38.071529,82.972740,36.191498,0.000000,111.759468,28.559265,62.708542,...,0.000000,23.594315,7.380337,0.000000,0.000000,82.827721,62.708542,55.920971,38.185688,6.900193
4,14.512540,9.859558,0.000000,0.000000,14.970598,3.751620,0.000000,8.679692,6.638978,7.691395,...,0.000000,0.000000,8.088406,0.000000,0.000000,0.000000,7.691395,14.410603,4.610927,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200944,382.744659,211.936432,38.326385,18.098677,119.760582,153.868317,0.000000,126.257973,78.301422,211.093262,...,2.886751,3.332076,55.987770,2.886751,4.041461,47.940018,211.093262,222.654877,53.972034,8.681061
200945,9.548791,14.349356,1.082397,1.537274,60.724392,44.907494,0.000000,128.896027,11.912778,32.791611,...,0.000000,4.133061,31.728575,0.000000,2.521910,64.268562,32.791611,53.621864,2.046550,0.398523
200946,18.610582,16.032692,4.826458,7.265290,8.801373,19.183283,0.000000,19.183231,4.266632,6.990929,...,0.000000,9.923802,0.000000,0.000000,0.000000,15.684353,6.990929,22.950951,3.165550,0.000000
200947,27.634529,35.283852,23.551992,19.362024,24.745279,37.829575,0.000000,59.436279,28.378330,19.364517,...,0.000000,0.000000,15.975679,0.000000,0.000000,26.044426,19.364517,30.157501,20.877047,4.509120
200948,150.261230,158.244888,39.956760,53.504635,210.071228,63.910709,17.141611,126.851051,83.914764,103.071167,...,0.000000,24.734453,22.915462,0.000000,1.692491,112.513786,103.071167,101.843338,15.483871,2.293463

In [ ]:
user_profile.toarray()[1].shape

(24,)

In [ ]:
tfidf_matrix.shape, user_profile.toarray()[1].shape

((87585, 24), (24,))

In [ ]:
# Descending
np.argsort([10, 5, -1, 50])[::-1]

array([3, 0, 1, 2], dtype=int64)

In [ ]:
user_vector = tfidf_matrix @ user_profile.toarray()[20]

In [ ]:
score_idx = np.argsort(user_vector)[::-1][:5]
score_idx

array([25042, 12880, 34202, 65594, 39478], dtype=int64)

# Deployment

In [ ]:
import joblib

joblib.dump(tfidf_matrix, 'tfidf_matrix.pkl')
joblib.dump(user_profile, 'user_profile.pkl')

movies.to_parquet('movies.parquet')

In [ ]:
import streamlit as st

In [ ]:
%%writefile recommendation_app.py

import streamlit as st
import pandas as pd
import joblib
import numpy as np

tfidf_matrix = joblib.load('tfidf_matrix.pkl')
user_profile = joblib.load('user_profile.pkl')
movies = pd.read_parquet('movies.parquet')

user_id = st.number_input('User ID', step= 1)
top_n = st.slider('Top N', step= 1)

user_vector = tfidf_matrix @ user_profile.toarray()[user_id]

score_idx = np.argsort(user_vector)[::-1][:top_n]

st.subheader('Top Recommended Movies')

for idx, mov in enumerate(movies['title'].iloc[score_idx]):

    st.write(f'{idx + 1} : {mov}')

Overwriting recommendation_app.py

In [ ]:
! streamlit run recommendation_app.py

^C